# Generated by Django 2.1.5 on 2021-01-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210105_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, max_length=1000.0, null=True, upload_to='files/'),
        ),
    ]
