# Generated by Django 2.1.5 on 2021-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210106_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='journal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
